### ISSUE TITLE
add russian bad works (now only 151, but we have more!)

### ISSUE THREAD

**Issue by mishagrol** [shutterstock/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words#196]
падла
нафиг
жлоб
мразь
нахуй
гад
хуйлуша
ебаный
идиот
козел
негодяй
дегенерат
трахнуть
мразота
нахуя
ебанутые
дурак
кретин
хуипи
падла
онанист
дифичент
мерзавец
говно собачье
хуя
хуй пинать
гнидр
блять
ебаный 
впизду
мать твою
засранец вонючий
пидрила
ублюдок
мудак
чёртов
дибилы

**Comment by LDNOOBWV2** [comment]
I created a new project as this here is not maintained anymore, including your list:
https://github.com/LDNOOBWV2/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words_V2/

and I found some more Russian lists, so now there are really many

**Comment by mishagrol** [comment]
Great! Thank you
