### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by jeremydw** [shutterstock/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words#5]
Hi there, thanks for providing this dirty word list, and in several languages no less. Would it be possible to add an official LICENSE file to this repository? I'd be happy to send a pull request containing the right license, just let me know which license you prefer.

If you do not want to add the LICENSE file, would someone be able to describe the license in this issue? Thank you.

**Comment by 26p4yt29v5-pixel** [comment]
تعال مص
