### ISSUE TITLE
ethical slut?

### ISSUE THREAD

**Issue by shadowcat-mst** [shutterstock/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words#59]
That's ... a book about open relationships and polyamory ... I ... wtf is that doing on there?

(note that I'm absolutely *not* intending to get into an argument about the reason, I just can't work out what the heck the reason is)

**Comment by patch** [comment]
Thanks for asking and bringing this to our attention! That entry has existed in the project as far back as we have version control history and nobody who started the project is actively involved anymore. I agree that it doesn’t belong here so I’ve removed it.
